import SwiftUI

struct MiniMap:View {
    let game:ArenaSimulation;let onPan:(V2?)->Void;let onPing:(V2)->Void
    var body:some View{Canvas {ctx,size in
        func point(_ p:V2)->CGPoint{CGPoint(x:p.x/100*size.width,y:(1-p.y/100)*size.height)}
        ctx.fill(Path(CGRect(origin:.zero,size:size)),with:.color(Color(red:0.12,green:0.24,blue:0.22)))
        for lane in Battlefield.lanes {var path=Path();path.move(to:point(lane[0]));for p in lane.dropFirst(){path.addLine(to:point(p))};ctx.stroke(path,with:.color(.white.opacity(0.20)),lineWidth:5)}
        var river=Path();river.move(to:point(V2(7,93)));river.addLine(to:point(V2(93,7)));ctx.stroke(river,with:.color(.cyan.opacity(0.23)),lineWidth:7)
        let allies=game.units.filter{$0.team==0 && $0.alive}
        for x in 0..<14 {for y in 0..<14 {let p=V2((Double(x)+0.5)*100/14,(Double(y)+0.5)*100/14);if !allies.contains(where:{$0.p.distance(p)<($0.isHero ? 14:10)}) {let origin=point(V2(Double(x)*100/14,Double(y+1)*100/14));ctx.fill(Path(CGRect(x:origin.x,y:origin.y,width:size.width/14+0.5,height:size.height/14+0.5)),with:.color(.black.opacity(0.5)))}}}
        for u in game.units where u.alive && game.visible(u,to:0){let p=point(u.p);let r:CGFloat=u.id==game.playerID ? 4:u.isHero ? 3.3:u.structure ? 2.7:u.neutral ? 2.5:1.1;let color:Color=u.id==game.playerID ? .white:u.team==0 ? .cyan:u.team==1 ? .pink:.yellow
            let rect=CGRect(x:p.x-r,y:p.y-r,width:r*2,height:r*2);ctx.fill(u.structure ? Path(rect):Path(ellipseIn:rect),with:.color(color));if u.id==game.playerID{ctx.stroke(Path(ellipseIn:rect.insetBy(dx:-1.8,dy:-1.8)),with:.color(.cyan),lineWidth:1)}
        }
        let player=point(game.player.p);ctx.stroke(Path(CGRect(x:player.x-size.width*0.14,y:player.y-size.height*0.11,width:size.width*0.28,height:size.height*0.22)),with:.color(.white.opacity(0.4)),lineWidth:0.7)
        if game.pingUntil>game.time,let p=game.pingPoint{let c=point(p);let r=CGFloat(4+sin(game.time*8)*2);ctx.stroke(Path(ellipseIn:CGRect(x:c.x-r,y:c.y-r,width:r*2,height:r*2)),with:.color(.yellow),lineWidth:2)}
    }.clipShape(RoundedRectangle(cornerRadius:10)).overlay(RoundedRectangle(cornerRadius:10).stroke(Color.white.opacity(0.35),lineWidth:1)).gesture(DragGesture(minimumDistance:0).onChanged{value in onPan(V2(Double(value.location.x/140)*100,(1-Double(value.location.y/140))*100))}.onEnded{value in onPan(nil);if hypot(value.translation.width,value.translation.height)<8{onPing(Battlefield.clamp(V2(Double(value.location.x/140)*100,(1-Double(value.location.y/140))*100)))}}).accessibilityLabel("Minimap. Drag to inspect; tap to ping.")}
}
struct ShopView:View {
    @ObservedObject var session:BattleSession;@Environment(\.dismiss)var dismiss;@State var group:ItemGroup?;@State var selected=0
    var g:ArenaSimulation{session.game}
    var body:some View {NavigationStack {VStack(alignment:.leading,spacing:12){
        HStack{Text("\(Int(g.player.gold)) gold").font(.headline).foregroundColor(.yellow);Spacer();Text("Buy anywhere · 6 equipment slots").font(.caption).foregroundColor(.secondary)}
        HStack{filter(nil);ForEach(ItemGroup.allCases,id:\.self){filter($0)}}
        HStack(alignment:.top,spacing:16){ScrollView {LazyVGrid(columns:[GridItem(.adaptive(minimum:135))],spacing:8){ForEach(Armory.items.filter{group == nil || $0.group==group}){item in Button{selected=item.id}label:{VStack(alignment:.leading,spacing:6){HStack{Image(systemName:item.icon).foregroundColor(.yellow);Text(item.name).font(.caption.bold())};Text(item.description).font(.system(size:10)).foregroundColor(.secondary).lineLimit(3);Text(g.player.items.contains(item.id) ? "OWNED":"\(g.price(item,for:g.player)) gold").font(.caption.bold()).foregroundColor(.yellow)}.frame(maxWidth:.infinity,minHeight:80,alignment:.topLeading).padding(10).background(selected==item.id ? Color.cyan.opacity(0.13):Color.white.opacity(0.04),in:RoundedRectangle(cornerRadius:9))}.buttonStyle(.plain)}}}
            VStack(alignment:.leading,spacing:9){let item=Armory.items[selected];Image(systemName:item.icon).font(.largeTitle).foregroundColor(.yellow);Text(item.name).font(.headline);Text(item.description).font(.caption).foregroundColor(.secondary);if let component=item.component{Text("Upgrades from \(Armory.items[component].name). Its full cost is credited.").font(.caption2).foregroundColor(.cyan)};Button("Buy · \(g.price(item,for:g.player)) gold"){_=g.buy(item.id,for:g.player);session.revision+=1}.buttonStyle(.borderedProminent).disabled(g.player.items.contains(item.id) || g.player.gold<Double(g.price(item,for:g.player)));Spacer();Text("INVENTORY · tap to sell for 60%").font(.system(size:8,weight:.bold)).foregroundColor(.secondary);ForEach(Array(g.player.items.enumerated()),id:\.offset){slot,id in Button{g.sell(slot);session.revision+=1}label:{HStack{Image(systemName:Armory.items[id].icon);Text(Armory.items[id].name).font(.caption);Spacer();Text("Sell").font(.caption2)}}}.frame(width:220)
        }
    }.padding().background(Color(red:0.035,green:0.075,blue:0.11)).navigationTitle("Equipment").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.confirmationAction){Button("Close"){dismiss()}}}}}
    func filter(_ value:ItemGroup?)->some View {Button(value?.rawValue ?? "All"){group=value}.font(.caption.bold()).buttonStyle(.bordered).tint(group==value ? .cyan:.gray)}
}
struct ScoreboardView:View {
    let game:ArenaSimulation;@Environment(\.dismiss)var dismiss
    var body:some View{NavigationStack{ScrollView{VStack(spacing:14){ForEach(0...1,id:\.self){team in VStack(alignment:.leading,spacing:8){HStack{Text(team==0 ? "DAWN ALLIANCE":"DUSK LEGION").foregroundColor(team==0 ? .cyan:.pink);Spacer();Text("\(Int(game.heroes.filter{$0.team==team}.reduce(0){$0+$1.earnedGold})) gold")}.font(.caption.bold());ForEach(game.heroes.filter{$0.team==team}){u in HStack(spacing:12){Image(systemName:u.def.role.icon).foregroundColor(Color(UIColor(rgb:u.def.color))).frame(width:24);VStack(alignment:.leading){Text(u.name+(u.id==game.playerID ? " · YOU":"")).font(.caption.bold());Text("Lv \(u.level) · \(u.def.role.rawValue)").font(.caption2).foregroundColor(.secondary)}.frame(width:125,alignment:.leading);Text("\(u.kills) / \(u.deaths) / \(u.assists)").font(.caption.monospacedDigit()).frame(width:80);HStack(spacing:5){ForEach(u.items,id:\.self){id in Image(systemName:Armory.items[id].icon).font(.caption).foregroundColor(.yellow).frame(width:22,height:22).background(.white.opacity(0.07),in:RoundedRectangle(cornerRadius:4))}};Spacer();Text("DMG \(Int(u.dealt))").font(.caption2.monospacedDigit());if !u.alive {Text("\(Int(ceil(u.respawn)))s").font(.caption).foregroundColor(.pink)}}.padding(8).background(.white.opacity(0.035),in:RoundedRectangle(cornerRadius:8))}}}}.padding()}.background(Color(red:0.035,green:0.075,blue:0.11)).navigationTitle("Match scoreboard").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.confirmationAction){Button("Close"){dismiss()}}}}}
struct GuideView:View {
    @Environment(\.dismiss)var dismiss
    var body:some View{NavigationStack{List{
        Section("Win the match"){Text("Destroy the enemy Nexus. Each lane has three turrets: the outer turret must fall before the next becomes vulnerable. Clear one lane of turrets to expose the Nexus.");Text("Your four allied bots and five opposing bots play the lanes, buy equipment, retreat to heal, and contest nearby objectives.")}
        Section("Controls"){Text("Move with the left joystick. Hold Attack for repeated basic attacks. The smaller attack buttons prioritize minions or turrets.");Text("Tap a skill for automatic aiming. Drag a skill to aim and release to cast. Drag more than 140 points from its starting point to cancel.");Text("Use the + buttons to spend skill points. The ultimate unlocks at level 4, with upgrades at 8 and 12. Hero level caps at 15.");Text("Tap the minimap to ping a position to your allies. Hold and drag it to move the camera temporarily.")}
        Section("Resources and combat"){Text("Last hits award extra gold; nearby allies share experience and receive gold. Equipment is available from level 1. Carry up to six items and one pair of boots. Components reduce upgrade cost.");Text("Armor reduces physical damage; resistance reduces magic damage. Penetration lowers those defenses. Shields absorb damage before health.");Text("Recall channels for six seconds and is interrupted by movement, attacks, skills, or incoming damage. Regen restores health and mana until damaged. The fountain heals quickly.")}
        Section("Jungle and vision"){Text("Brush conceals units unless enemies enter the same patch, approach very closely, or the unit reveals itself by fighting. The minimap only shows enemies your team can see.");Text("Jungle camps spawn at 0:10. Azure and Ember Guardians grant temporary buffs. The Tide Sentinel first spawns at 2:00 and grants team gold, XP, and shields. The Rift Colossus first spawns at 8:00 and sends an allied siege monster down a lane.");Text("Turrets favor minions, but will retaliate when a nearby hero attacks an ally. Repeated turret hits become stronger. Structures resist damage without an attacking minion wave.")}
        Section("This build"){Text("Aether Rift is an original offline MOBA prototype. Its character models, map, abilities, effects, and audio are original. It has no online matchmaking, ranked service, accounts, or purchases.");Text("Practice grants extra gold and experience, earlier bosses, and reduced incoming damage. Settings pause the match and provide practice controls.")}
    }.navigationTitle("How to play").toolbar{ToolbarItem(placement:.confirmationAction){Button("Done"){dismiss()}}}}}
