name: MaiChartMaker
options:
  bundleIdPrefix: com.rvmendillo
  deploymentTarget:
    iOS: "16.0"
packages:
  SwiftMP3:
    url: https://github.com/mierau/swift-mp3.git
    revision: da763ee1749ee1e47916ec49915127b82cf179ba
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
  FFmpegKit:
    url: https://github.com/jaywcjlove/ffmpeg-kit.git
    revision: 0243a6a262944e2e6cd1dd9603122108594d182a
targets:
  MaiChartMaker:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: SwiftMP3
      - package: ZIPFoundation
      - package: FFmpegKit
        product: ffmpegkit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rvmendillo.maichartmaker
        PRODUCT_NAME: MaiChartMaker
        SWIFT_VERSION: 5.10
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: MaiChart Maker
        UILaunchScreen: {}
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UIApplicationSupportsIndirectInputEvents: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        CFBundleDocumentTypes:
          - CFBundleTypeName: Audio
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.mp3
              - public.mpeg-4-audio
              - public.audio
